import type { Config } from 'tailwindcss';

// Token block copied verbatim from the Stitch export (Ui/*/code.html, tailwind-config script).
const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#fefcff',
        'error-container': '#ffdad6',
        'surface-dim': '#cbdbf5',
        'on-primary': '#ffffff',
        'outline-variant': '#c5c5d3',
        'on-background': '#0b1c30',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#444651',
        'surface-variant': '#d3e4fe',
        'primary-fixed-dim': '#b6c4ff',
        'on-primary-container': '#90a8ff',
        'on-secondary-fixed': '#00174b',
        outline: '#757682',
        'on-primary-fixed': '#00164e',
        'surface-container': '#e5eeff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'secondary-fixed': '#dbe1ff',
        'inverse-on-surface': '#eaf1ff',
        'primary-container': '#1e3a8a',
        'secondary-fixed-dim': '#b4c5ff',
        background: '#f8f9ff',
        'surface-container-low': '#eff4ff',
        primary: '#00236f',
        'surface-container-highest': '#d3e4fe',
        'surface-tint': '#4059aa',
        'tertiary-fixed': '#9cf2e8',
        'on-primary-fixed-variant': '#264191',
        'surface-container-high': '#dce9ff',
        tertiary: '#00312d',
        'surface-container-lowest': '#ffffff',
        surface: '#f8f9ff',
        'tertiary-container': '#004944',
        'on-error-container': '#93000a',
        'inverse-surface': '#213145',
        'on-tertiary-fixed': '#00201d',
        'on-tertiary-fixed-variant': '#00504a',
        'surface-bright': '#f8f9ff',
        'secondary-container': '#316bf3',
        'on-tertiary-container': '#65bbb1',
        'inverse-primary': '#b6c4ff',
        secondary: '#0051d5',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#dce1ff',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#80d5cb',
        'on-secondary-fixed-variant': '#003ea8',
      },
      borderRadius: { DEFAULT: '0.125rem', lg: '0.25rem', xl: '0.5rem', full: '0.75rem' },
      spacing: {
        'space-xs': '0.25rem',
        'gutter-dense': '0.5rem',
        'space-lg': '1.5rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        margin: '1.5rem',
        'margin-compact': '1rem',
        gutter: '1rem',
        'space-xl': '2rem',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'display-lg': ['Inter'],
        'code-tabular': ['JetBrains Mono'],
        'code-sm': ['JetBrains Mono'],
        'body-md': ['Inter'],
        'headline-md': ['Inter'],
        'label-md': ['Inter'],
        'body-sm': ['Inter'],
        'headline-lg': ['Inter'],
        'label-lg': ['Inter'],
        'headline-xl': ['Inter'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'body-lg': ['15px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'code-tabular': ['12px', { lineHeight: '16px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'code-sm': ['11px', { lineHeight: '14px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'label-md': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-lg': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-xl': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};

export default config;
