CREATE INDEX IF NOT EXISTS idx_organizations_parent ON organizations(parent_organization_id);
CREATE INDEX IF NOT EXISTS idx_jurisdictions_parent ON jurisdictions(parent_jurisdiction_id);
CREATE INDEX IF NOT EXISTS idx_offices_parent ON offices(parent_office_id);
CREATE INDEX IF NOT EXISTS idx_positions_office_type ON positions(office_id, position_type_id) WHERE status <> 'INACTIVE';
CREATE INDEX IF NOT EXISTS idx_projects_department ON projects(department_organization_id, operational_status);
CREATE INDEX IF NOT EXISTS idx_projects_office ON projects(owning_office_id, operational_status);
CREATE INDEX IF NOT EXISTS idx_projects_jurisdiction ON projects(primary_jurisdiction_id, operational_status);
CREATE INDEX IF NOT EXISTS idx_projects_type_status ON projects(project_type_id, operational_status, lifecycle_stage);
CREATE INDEX IF NOT EXISTS idx_projects_attributes_gin ON projects USING GIN(attributes);
CREATE INDEX IF NOT EXISTS idx_project_sites_coords ON project_sites(latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_proposals_project_status ON project_proposals(project_id, status, version_no DESC);
CREATE INDEX IF NOT EXISTS idx_budget_project_year ON project_budget_allocations(project_id, financial_year);
CREATE INDEX IF NOT EXISTS idx_design_packages_project ON design_estimate_packages(project_id, version_no DESC);
CREATE INDEX IF NOT EXISTS idx_boq_project ON boq_items(project_id);
CREATE INDEX IF NOT EXISTS idx_rule_versions_code_effective ON rule_versions(rule_code, effective_from, effective_to, version_no DESC);
CREATE INDEX IF NOT EXISTS idx_rule_versions_source ON rule_versions(source_id, verification_status);
CREATE INDEX IF NOT EXISTS idx_authority_rules_rule_version ON authority_rules(rule_version_id);
CREATE INDEX IF NOT EXISTS idx_workflow_templates_lookup ON workflow_templates(project_type_id, department_organization_id, status);
CREATE INDEX IF NOT EXISTS idx_workflow_edges_from ON workflow_edge_templates(from_node_template_id);
CREATE INDEX IF NOT EXISTS idx_workflow_edges_to ON workflow_edge_templates(to_node_template_id);
CREATE INDEX IF NOT EXISTS idx_workflow_instance_dependencies_from ON workflow_instance_dependencies(from_node_instance_id, state);
CREATE INDEX IF NOT EXISTS idx_workflow_instance_dependencies_to ON workflow_instance_dependencies(to_node_instance_id, state);
CREATE INDEX IF NOT EXISTS idx_approvals_status ON approval_cases(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_clearances_project_status ON clearances(project_id, status);
CREATE INDEX IF NOT EXISTS idx_documents_project_type ON documents(project_id, document_type_id, status);
CREATE INDEX IF NOT EXISTS idx_document_versions_document ON document_versions(document_id, version_no DESC);
CREATE INDEX IF NOT EXISTS idx_tenders_project_status ON tenders(project_id, status);
CREATE INDEX IF NOT EXISTS idx_contracts_contractor ON contracts(contractor_id, status);
CREATE INDEX IF NOT EXISTS idx_work_orders_project_status ON work_orders(project_id, status);
CREATE INDEX IF NOT EXISTS idx_milestones_project_status ON milestones(project_id, status, planned_finish);
CREATE INDEX IF NOT EXISTS idx_measurements_project_status ON measurements(project_id, status, measured_at);
CREATE INDEX IF NOT EXISTS idx_bills_project_status ON bills(project_id, technical_status, financial_status);
CREATE INDEX IF NOT EXISTS idx_issues_project_status ON issues(project_id, status, severity, due_at);
CREATE INDEX IF NOT EXISTS idx_variations_project_status ON variations(project_id, status);
CREATE INDEX IF NOT EXISTS idx_dlp_defects_status ON dlp_defects(dlp_period_id, status, due_at);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notification_recipients(user_id, notification_id) WHERE read_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_ai_runs_project_time ON ai_runs(project_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_suggestions_project_status ON ai_suggestions(project_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_project_members_project ON project_members(project_id, member_type);
